// src/components/progress-bar/progress-bar.tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'an-progress-bar'
})
export class AnProgressBar {

  @Prop() value: number = 0;
  @Prop() theme: string = 'primary';

  render() {
    const classes = [
      'an-progress-bar',
      `an-progress-bar-${this.theme}`
    ].join(' ');

    return (
      <div class={classes}>
        <div class="an-progress-bar-value" style={ { width: `${this.value}%` } }></div> 
      </div>
    );
  }
}

// src/components/progress-bar/progress-bar.vue
<template>
  <div class="an-progress-bar" :class="classes">
    <div class="an-progress-bar-value" :style="inlineStyle"></div>
  </div>
</template>

<script>
export default {
  name: 'an-progress-bar',

  props: {
    value: {
      type: Number,
      default: 0
    },
    theme: {
      type: String,
      default: 'primary'
    }
  },

  computed: {
    classes() {
      return {
        [`an-progress-bar-${this.theme}`]: true
      };
    },
    inlineStyle() {
      return {
        width: `${this.value}%`
      };
    }
  }
};
</script>
