// src/components/progress-bar/progress-bar.tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'an-progress-bar'
})
export class AnProgressBar {

  @Prop() value: number = 0;
  @Prop() theme: string = 'primary';

  render() {
    const classes = [
      'an-progress-bar',
      `an-progress-bar-${this.theme}`
    ].join(' ');

    return (
      <div class={classes}>
        <div class="an-progress-bar-value" style={ { width: `${this.value}%` } }></div> 
      </div>
    );
  }
}

// demo/src/views/progress-bar.vue
<template>
    <div>
        <an-progress-bar class="mg-bt" theme="primary" :value="5"></an-progress-bar>
        <an-progress-bar class="mg-bt" theme="secondary" :value="25"></an-progress-bar>
        <an-progress-bar class="mg-bt" theme="success" :value="50"></an-progress-bar>
        <an-progress-bar class="mg-bt" theme="warn" :value="75"></an-progress-bar>
        <an-progress-bar class="mg-bt" theme="danger" :value="85"></an-progress-bar>
        <an-progress-bar theme="info" :value="100"></an-progress-bar>
    </div>
</template>
