// src/components/input-file/input-file.vue
<template>
  <div>
    <input type="file" class="an-input-file" :class="classes" @change="onChange" :accept="accept" :multiple="multiple" :id="id">
    <label class="an-input-file-label" :for="id">
      <div class="an-input-file-btn">
        {{ placeholder }}
      </div>
      <div class="an-input-file-filename">
        {{ selectedFilesText }}
      </div>
    </label>
  </div>
</template>

<script>
function applyEllipsis(text) {
  if (text.length > 15) {
    return text.substr(0, 15) + '...';
  }

  return text;
}

const defaultMessages = {
  noSelectedFiles: () => 'No file selected',
  oneSelectedFile: file => applyEllipsis(file.name),
  manySelectedFiles: files => `${files.length} files`
};

export default {
  name: 'an-input-file',

  props: {
    messages: {
      type: Object,
      default: () => ({})
    },
    placeholder: {
      type: String,
      default: 'Select file'
    },
    theme: {
      type: String,
      default: 'primary'
    },
    multiple: {
      type: Boolean,
      default: false
    },
    accept: {
      type: String
    }
  },

  data() {
    return {
      id: String(Date.now()),
      selectedFiles: []
    };
  },

  computed: {
    mergedMessages() {
      return { ...defaultMessages, ...this.messages };
    },
    classes() {
      return {
        [`an-input-file-${this.theme}`]: true
      };
    },
    selectedFilesText() {
      if (!this.selectedFiles.length) {
        return this.mergedMessages.noSelectedFiles();
      }

      if (this.selectedFiles.length === 1) {
        return this.mergedMessages.oneSelectedFile(this.selectedFiles[0]);
      }

      return this.mergedMessages.manySelectedFiles(this.selectedFiles);
    }
  },
  methods: {
    onChange(event) {
      const files = Array.from(event.target.files);

      this.readFiles(files).then(data => {
        this.$emit('change', data);
      });

      this.selectedFiles = files;
    },

    readFiles(files) {
      const promises = files.map(
        item =>
          new Promise(resolve => {
            const reader = new FileReader();

            reader.onload = () => {
              resolve(reader.result);
            };

            reader.readAsDataURL(item);
          })
      );

      return Promise.all(promises);
    }
  }
};
</script>

// src/components/input-file/input-file.tsx
import { Component, Prop, Event, EventEmitter, State, Method } from '@stencil/core';

@Component({
    tag: 'an-input-file'
})
export class InputFile {

    selectedFilesMessageFn: (files: File[]) => string = files => {
        if (!files.length) {
            return 'No file selected';
        }

        if (files.length === 1) {
            if (files[0].name.length > 15) {
                return files[0].name.substr(0, 15) + '...';
            }

            return files[0].name;
        }

        return `${files.length} files`;
    };

    id = String(Date.now());

    @State() state: File[] = [];

    @Prop() placeholder: string = 'Select file';

    @Prop() theme: string = 'primary';

    @Prop() multiple: boolean = false;

    @Prop() accept: string;

    @Event({ eventName: 'onchange' })
    onChangeEmitter: EventEmitter;

    @Method()
    setSelectedFilesMessage(fn: (files: File[]) => string) {
        this.selectedFilesMessageFn = fn;
        
        // re-render
        this.state = this.state.slice();
    }

    onChange(event) {
        const files = Array.from<File>(event.target.files);

        this.readFiles(files)
            .then(data => {
                this.onChangeEmitter.emit(data);
            });

        this.state = files;
    }

    readFiles(files: any[]) {
        const promises = files.map(item => new Promise(resolve => {
            const reader = new FileReader();

            reader.onload = () => {
                resolve(reader.result);
            }

            reader.readAsDataURL(item);
        }));

        return Promise.all(promises);
    }

    render() {

        const classes = [
            'an-input-file',
            `an-input-file-${this.theme}`
        ].join(' ');

        const selectedFilesText = this.selectedFilesMessageFn(this.state);

        return [
            <input class={classes}
                type="file"
                onChange={this.onChange.bind(this)}
                accept={this.accept}
                id={this.id}
                multiple={this.multiple} />,

            <label class="an-input-file-label" htmlFor={this.id}>
                <div class="an-input-file-btn">
                    {this.placeholder}
                </div>
                <div class="an-input-file-filename">
                    {selectedFilesText}
                </div>
            </label>

        ];
    }
}
